import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bill Divider',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1.0,
    maximumScale: 1.0,
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
